base_url = "https://minorgordon.net"
build_search_index = false
compile_sass = true
title = "Minor Gordon"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author = "Minor Gordon"
